### ISSUE TITLE
After binding value changes, the code block fails to update the corresponding value even if call StateHasChanged

### ISSUE THREAD

**Issue by SanYiKou** [MyNihongo/MudBlazor.Markdown#209] opened 2023-09-15 09:44 UTC
First, I would like to express my gratitude for providing such a great component. 
Regarding the relative issue #166, it seems that the issuer had already provided an example code. However, the author used a different test code instead of the code-block to attempt to replicate the problem.
I have encountered the same problem when doing code-block re-rendering while other parts are OK.

**Comment by MihailsKuzmins** [comment] 2023-09-18 02:44
@SanYiKou 
thanks. Regarding that issue you have mentioned. I was not able to reproduce the issue and the author has not provided a complete solution where it fails. So if you have encountered this problem could you please provide a git repository (probably on GitHub) where it can be reproduced?

**Comment by my-nihongo** [comment] 2023-09-24 12:58
@SanYiKou
Could you please provide a repository where the reported issue can be reproduced. Otherwise, we will be forced to close the issue assuming that it is no longer relevant.

Thank you for your understanding.

**Closed** 2024-05-15 11:34 UTC
Labels: bug

**Comment by MihailsKuzmins** [comment] 2024-05-16 03:39
@tveito Thanks for providing the repo. That helped a lot.
