### ISSUE TITLE
Table not showing when indented

### ISSUE THREAD

**Issue by iroelperez** [MyNihongo/MudBlazor.Markdown#144] opened 2023-01-06 16:18 UTC
Table is not showing using <MudMarkdown> if there is any indentation in the content, se example below: 

```
## Prereq
The following requirements must be met outside this Terraform code in advance.

1. Created a new resource group..
2. Created a new AAD group using naming convention..
3. Created a new AAD group using naming convention..
4. Created a separate storage account..
5. Created a new app registration..
     
  |Permission | Type | Granted Through|
  |--|--|--|
  |User.Read | Delegated | Admin consent|
  | User.ReadBasic.All |Delegated| Admin consent|
  |User.Read.All|Delegated| Admin consent|
  |Directory.Read.Alll|Delegated| Admin consent|
  |Directory.AccessAsUser.All|Delegated| Admin consent|
  |User.Invite.All|Application| Admin consent|
  |Directory.Read.All|Application| Admin consent|
  |User.Read.All|Application| Admin consent|
  - Granted permissions User.Invite.All and GroupMember.ReadWrite.All. Admin consent has been granted
 
6. Create a new app registration..
7. Created the key vault..
8. Created secrets..

```

**Comment by MihailsKuzmins** [comment] 2023-01-13 04:20
I cannot reproduce your issue in the develop branch. For me the table is rendered inside the list.
Probably there were some fixed in the markdown parser.
![image](https://user-images.githubusercontent.com/47413092/212236498-f366f50f-b294-4a09-90aa-79df8f453242.png)  
![image](https://user-images.githubusercontent.com/47413092/212236369-ce95b8e8-50dc-4f0a-9565-f141ca3f8fa1.png)

**Closed** 2023-01-14 09:40 UTC
Labels: bug
